### ISSUE TITLE
Matt wants compare_table added to check_references

### ISSUE THREAD

**Issue by jwhite3** [Vb2341/ReDCaT#15]
This seem like it should be easy, but it might be a little complicated. 
We'd need to be able to determine if a reference file is a table, and then capture the output in a meaningful way, and then figure out if we can automate the process of checking the differences

**Comment by Vb2341** [comment]
So I don't think it'd be too hard to do this.  We can actually just call compare table in the code rather than writing our own stuff.  However, the user would have to supply their own table to compare it to, and doing anything to find that automatically is a whoooole different task entirely.

**Comment by jwhite3** [comment]
After more thought.. nah. crds.certify is checking table values when it can, and this kind of falls on the instrument teams anyways..
