### ISSUE TITLE
Replace info_ref_files with something that works

### ISSUE THREAD

**Issue by jwhite3** [Vb2341/ReDCaT#17]
Just kidding.. just something that's better, more robust, and well documented

**Comment by gkanarek** [comment]
What is it supposed to do?

**Comment by jwhite3** [comment]
Basically it's supposed to check JWST keywords. Currently crds.certify checks for mandatory keywords, but (if I'm remembering correctly) it doesn't check for invalid keyword-instrument combinations. It just looks for a "soup" of keywords. 

This tool is meant to check more explicitly if the keywords and values are correct for each instrument. This is kind of a simplified summary and something that we were going to discuss (likely) in more detail at the coding meeting.

**Comment by jwhite3** [comment]
Turns out that crds.certify actually checks these things so....
