### ISSUE TITLE
More verbose output for warnings

### ISSUE THREAD

**Issue by jwhite3** [Vb2341/ReDCaT#20]
Matt suggested that he'd might like to have a more explicit record of warnings/errors that occur when certify is run. 

I suggested that we could increase the verbose setting in certify. I remember that we played around with this before and some weird stuff happened, but we should revisit it since we basically get no information about the warnings as is

**Comment by gkanarek** [comment]
Definitely should either scale back the verbosity, or find some way to collect the errors/warnings and put them at the end, since this completely overloads the output. Or maybe just store the full, verbose output in a file for later perusal?

**Comment by jwhite3** [comment]
Yeah... It's a little gross

**Comment by jwhite3** [comment]
The plan is to clean up the output to make it more human readable but still maintain all of the info 
@Vb2341

**Comment by jwhite3** [comment]
I think this can be closed for now
