### ISSUE TITLE
realtime output from subprocesses 

### ISSUE THREAD

**Issue by jwhite3** [Vb2341/ReDCaT#25]
I've been looking into this, and I think I can do it. I'll play around with it some soon. It involves using the read method of the subprocess

**Comment by gkanarek** [comment]
Perhaps [this](https://stackoverflow.com/a/6414278/3225754) is the way to go? You've probably already seen it, but I figured I'd keep it here for easy access.

**Comment by jwhite3** [comment]
Yep, that's what I'm playing with now and testing. Good call adding the link!

**Comment by jwhite3** [comment]
#45

**Comment by jwhite3** [comment]
DONE as per #45
