### ISSUE TITLE
Make a "submit" tool for instrument teams

### ISSUE THREAD

**Issue by jwhite3** [Vb2341/ReDCaT#26]
The idea is to make a tool that instrument teams would use to deliver files. 
this tool would do the following:

1. create the delivery directory 
2. copy files over
3. change permissions

Optional: we could potentially add a call to check_references so that when they deliver their files it automatically verifies/checks but I'm a little worried about that

**Comment by gkanarek** [comment]
Let me know if you'd like any input for this.

**Comment by jwhite3** [comment]
Sure! Once I have something I'll make a pull request and have you guys take a look

**Comment by jwhite3** [comment]
pull request #27
