### ISSUE TITLE
Add json checker to check_references.py

### ISSUE THREAD

**Issue by jwhite3** [Vb2341/ReDCaT#28]
Currently we have instrument teams doing this independently, but for consistency we should just add it to the checker script so that it can uniformly handle everything

**Comment by Vb2341** [comment]
If these are only delivered for the JWST ETC, then they are already in the JWST ETC script.  Perhaps we should make a module from which we can import our fits/json/asdf checker.

**Comment by Vb2341** [comment]
Imma go ahead and close this, as all the json stuff is handled with the jwst_etc script.
