### ISSUE TITLE
update checksum and datasum keywords in reference files 

### ISSUE THREAD

**Issue by jwhite3** [Vb2341/ReDCaT#32]
I think this issue is resolve upon renaming the file using uniqname for HST, but just to be sure (especially for JWST) we may want to take care of this before running crds.certify in the check_reference tool. 

Todd mentioned that CRDS may crash due to the checksum/datasum keyword warnings when submitting

**Comment by Vb2341** [comment]
Should we just add a step that uses astropy to either remove or update the checksums in all extensions?  That should just be 3 or so lines right?

**Comment by jwhite3** [comment]
yeah it would be super easy. The question is whether or not we can just delete them. I'll check with Matt to see if there's a pressing need to keep them

**Comment by jwhite3** [comment]
Also, this exists: 

`fitscheck --write --force *.fits`

**Comment by Vb2341** [comment]
I think 15f7b22 should force updating these keywords, so it shouldn't matter if the delivered files had this messed up.  Easy fix.
