### ISSUE TITLE
verify deliver_files.py does not alter rename parameter

### ISSUE THREAD

**Issue by bhbrooks** [Vb2341/ReDCaT#37]
There have been few reports that somehow HST files are becoming renamed when delivered. Verify that this is not the result of the deliver_files.py script. If not, this could be an issue with CRDS.

**Comment by jwhite3** [comment]
This is something that occurs on the crds.submit side of things. It automatically configures the renaming option based on whether or not it's an HST or JWST file. Or at least that's how it's been working... Todd may have changed this

**Comment by jwhite3** [comment]
This was a bug on the CRDS side of things, but I've also made the call to crds.submit more explicit in our code so that uniqname is manually turned off for HST files
