### ISSUE TITLE
Version check for JWST ETC json configuration files

### ISSUE THREAD

**Issue by matt-mcmaster** [Vb2341/ReDCaT#38]
The JWST ETC group will now be releasing json configuration file with a version number included.  This version number will be related to the current JWST ETC buile (e.g., for the files soon to come in, the version will be 1.2 or 1.2a).  Any subsequent changes to the template by the JWST ETC group will increment the version number to the next letter (1.2a to 1.2b, or 1.2 to 1.2b).  The ReDCaT Team will be provided the template files (instrument specific) at the same time the instrument teams are.  The jwst_etc_check script should open our version of the template file, read in the version number, and compare it to the version number in the json configuration file sent in by a given instrument team.  If the versions don't match, the script should issue a warning or error that the ReDCaT Team member handling the delivery needs to follow up on.  The version is indicated at the top of the file as the values of the keyword, "-delivered-for-version-"  The template files for the current release are now located in /user/mcmaster/CRDS/for_matt/templates  but could easily be housed elswhere.

**Comment by Vb2341** [comment]
This should be successfully implemented in  7aaee96

I noticed one other kind of JSON file in the directory (the cr file), the script doesn't know about these kinds of files yet, so more research will have to be done to support them, but the version checking has the framework to handle them already, so I'm closing this issue.
