### ISSUE TITLE
Create a work-around for fitsverify

### ISSUE THREAD

**Issue by jwhite3** [Vb2341/ReDCaT#4]
As per the meeting yesterday, Rossy thought it'd be a good idea to have a way to verify each fits file delivered until the astropy _verify_ is fixed

**Comment by Vb2341** [comment]
Seem to have got a workaround here (I have no idea why the def isn't in the code block):

`def verify_files(files):

    for f in files:
        print 'Verifying {}'.format(f)
        with warnings.catch_warnings(record=True) as w: # Workaround for astropy verify issues
            warnings.simplefilter("always") # Catch all warnings
            hdu = fits.open(f, mode='update') # Catches the 'fixable violations'
            hdu.verify('warn') # Catches the unfixable ones
            if len(w) == 0: # Check number of warnings, if =0 then file is good
                print f, 'PASSED VERIFICATION'
                hdu[0].header['VERIFIED'] = 'PASSED'
            else:
                print f, 'FAILED VERIFICATION'
                hdu[0].header['VERIFIED'] = 'FAILED'
                for warn in w:
                    print warn.message
            hdu.close(output_verify='ignore') `

Cool part, this prints exactly what each warning is too!
