### ISSUE TITLE
jwst_etc_check Not Moving Files

### ISSUE THREAD

**Issue by matt-mcmaster** [Vb2341/ReDCaT#40]
After Katie ran jwst_etc_check on the recent NIRISS configuration file, the logs reported that the file had been moved to /ifs/redcat/jwst/srefpipe/ETC/pandeia/pandeia_jwst_release_1.1dev/niriss.  However, upon checking the directory, the file had not been moved and the version of the file was the one from May 2017.  Note, the current directory is now 1.2dev and the configuration file was manually moved to the niriss subdirectory.  Not sure if Katie ran the tool as herself or srefpipe.

**Comment by Vb2341** [comment]
This and #41 are both related to the same issue.  When we wrote the script, the intention was to make the user explicitly tell the script to update the json files and move/update the json/fits files.  If the script is ran with the -h flag, the switches to enable these parts of the code should become obvious.

If there are new pandeia directories, the script also needs to be told that, the target directory can also be specified via the command line flags.

The rationale for this was to give the option to effectively 'dry run' the code without actually changing anything.  This allows verification that the correct sections would be updated.  If we want the default behavior to move/update the files, that's an easy change, but going backwards in the case that something's messed up will not be easy.
