### ISSUE TITLE
jwst_etc_check Not Updating the paths Section in the Configuration File

### ISSUE THREAD

**Issue by matt-mcmaster** [Vb2341/ReDCaT#41]
jwst_etc_check needs to update the fits file listing in the paths section to include the timestamp information.  For example, for the NIRISS configuration file recently sent in, the fits file listing needs to go from this:
    "clear": "optical/jwst_niriss_internaloptics-clear_throughput.fits",
    "clearp": "optical/jwst_niriss_internaloptics-clearp_throughput.fits",
    "f090w": "filters/jwst_niriss_f090w_trans.fits",
    "f115w": "filters/jwst_niriss_f115w_trans.fits",
    "f140m": "filters/jwst_niriss_f140m_trans.fits",
    "f150w": "filters/jwst_niriss_f150w_trans.fits",
    "f158m": "filters/jwst_niriss_f158m_trans.fits",
    "f200w": "filters/jwst_niriss_f200w_trans.fits",
    "f277w": "filters/jwst_niriss_f277w_trans.fits",
    "f356w": "filters/jwst_niriss_f356w_trans.fits",
    "f380m": "filters/jwst_niriss_f380m_trans.fits",
    "f430m": "filters/jwst_niriss_f430m_trans.fits",
    "f444w": "filters/jwst_niriss_f444w_trans.fits",
    "f480m": "filters/jwst_niriss_f480m_trans.fits",
    "gr150c": "blaze/jwst_niriss_gr150c-ordp1_speceff.fits",
    "gr150c_disp": "dispersion/jwst_niriss_gr150c-ordp1_disp.fits",
    "gr150c_r": "dispersion/jwst_niriss_gr150c-ordp1_disp.fits",
    "gr150r": "blaze/jwst_niriss_gr150r-ordp1_speceff.fits",
    "gr150r_disp": "dispersion/jwst_niriss_gr150r-ordp1_disp.fits",
    "gr150r_r": "dispersion/jwst_niriss_gr150r-ordp1_disp.fits",
    "gr700xd_1": "blaze/jwst_niriss_gr700xd-ord1_speceff.fits",
    "gr700xd_1_disp": "dispersion/jwst_niriss_gr700xd-ord1_disp.fits",
    "gr700xd_1_mask": "masks/jwst_niriss_soss-256-ord1_mask.fits",
    "gr700xd_1_mask96": "masks/jwst_niriss_soss-96-ord1_mask.fits",
    "gr700xd_1_r": "dispersion/jwst_niriss_gr700xd-ord1_disp.fits",
    "gr700xd_1_wavepix": "wavepix/jwst_niriss_soss-256-ord1_trace.fits",
    "gr700xd_1_wavepix96": "wavepix/jwst_niriss_soss-96-ord1_trace.fits",
    "gr700xd_2": "blaze/jwst_niriss_gr700xd-ord2_speceff.fits",
    "gr700xd_2_disp": "dispersion/jwst_niriss_gr700xd-ord2_disp.fits",
    "gr700xd_2_mask": "masks/jwst_niriss_soss-256-ord2_mask.fits",
    "gr700xd_2_r": "dispersion/jwst_niriss_gr700xd-ord2_disp.fits",
    "gr700xd_2_wavepix": "wavepix/jwst_niriss_soss-256-ord2_trace.fits",
    "gr700xd_2_wavepix96": "wavepix/jwst_niriss_soss-96-ord2_trace.fits",
    "gr700xd_3": "blaze/jwst_niriss_gr700xd-ord3_speceff.fits",
    "gr700xd_3_disp": "dispersion/jwst_niriss_gr700xd-ord3_disp.fits",
    "gr700xd_3_mask": "masks/jwst_niriss_soss-256-ord3_mask.fits",
    "gr700xd_3_r": "dispersion/jwst_niriss_gr700xd-ord3_disp.fits",
    "gr700xd_3_wavepix": "wavepix/jwst_niriss_soss-256-ord3_trace.fits",
    "gr700xd_3_wavepix96": "wavepix/jwst_niriss_soss-96-ord3_trace.fits",
    "internal": "optical/jwst_niriss_internaloptics_throughput.fits",
    "ipc_kernel": "../detector/hawaii_2rg_ipc_kernel.fits",
    "nrm": "filters/jwst_niriss_nrm_trans.fits",
    "qe": "qe/jwst_niriss_h2rg_qe.fits",
    "rn_corr": "../detector/h2rg_corr.fits"

to this:

    "clear": "optical/jwst_niriss_internaloptics-clear_throughput_20160902163017.fits",
    "clearp": "optical/jwst_niriss_internaloptics-clearp_throughput_20160902163017.fits",
    "f090w": "filters/jwst_niriss_f090w_trans_20160902163017.fits",
    "f115w": "filters/jwst_niriss_f115w_trans_20160902163017.fits",
    "f140m": "filters/jwst_niriss_f140m_trans_20160902163017.fits",
    "f150w": "filters/jwst_niriss_f150w_trans_20160902163017.fits",
    "f158m": "filters/jwst_niriss_f158m_trans_20160902163017.fits",
    "f200w": "filters/jwst_niriss_f200w_trans_20160902163017.fits",
    "f277w": "filters/jwst_niriss_f277w_trans_20160902163017.fits",
    "f356w": "filters/jwst_niriss_f356w_trans_20160902163017.fits",
    "f380m": "filters/jwst_niriss_f380m_trans_20160902163017.fits",
    "f430m": "filters/jwst_niriss_f430m_trans_20160902163017.fits",
    "f444w": "filters/jwst_niriss_f444w_trans_20160902163017.fits",
    "f480m": "filters/jwst_niriss_f480m_trans_20160902163017.fits",
    "gr150c": "blaze/jwst_niriss_gr150c-ordp1_speceff_20160902163017.fits",
    "gr150c_disp": "dispersion/jwst_niriss_gr150c-ordp1_disp_20160902163017.fits",
    "gr150c_r": "dispersion/jwst_niriss_gr150c-ordp1_disp_20160902163017.fits",
    "gr150r": "blaze/jwst_niriss_gr150r-ordp1_speceff_20160902163017.fits",
    "gr150r_disp": "dispersion/jwst_niriss_gr150r-ordp1_disp_20160902163017.fits",
    "gr150r_r": "dispersion/jwst_niriss_gr150r-ordp1_disp_20160902163017.fits",
    "gr700xd_1": "blaze/jwst_niriss_gr700xd-ord1_speceff_20160927172406.fits",
    "gr700xd_1_disp": "dispersion/jwst_niriss_gr700xd-ord1_disp_20160902163017.fits",
    "gr700xd_1_mask": "masks/jwst_niriss_soss-256-ord1_mask_20160902163017.fits",
    "gr700xd_1_mask96": "masks/jwst_niriss_soss-96-ord1_mask_20160902163017.fits",
    "gr700xd_1_r": "dispersion/jwst_niriss_gr700xd-ord1_disp_20160902163017.fits",
    "gr700xd_1_wavepix": "wavepix/jwst_niriss_soss-256-ord1_trace_20160929180722.fits",
    "gr700xd_1_wavepix96": "wavepix/jwst_niriss_soss-96-ord1_trace_20160927172406.fits",
    "gr700xd_2": "blaze/jwst_niriss_gr700xd-ord2_speceff_20160927172406.fits",
    "gr700xd_2_disp": "dispersion/jwst_niriss_gr700xd-ord2_disp_20160902163017.fits",
    "gr700xd_2_mask": "masks/jwst_niriss_soss-256-ord2_mask_20160902163017.fits",
    "gr700xd_2_r": "dispersion/jwst_niriss_gr700xd-ord2_disp_20160902163017.fits",
    "gr700xd_2_wavepix": "wavepix/jwst_niriss_soss-256-ord2_trace_20160929180722.fits",
    "gr700xd_2_wavepix96": "wavepix/jwst_niriss_soss-96-ord2_trace_20160927172406.fits",
    "gr700xd_3": "blaze/jwst_niriss_gr700xd-ord3_speceff_20160927172406.fits",
    "gr700xd_3_disp": "dispersion/jwst_niriss_gr700xd-ord3_disp_20160902163017.fits",
    "gr700xd_3_mask": "masks/jwst_niriss_soss-256-ord3_mask_20160902163017.fits",
    "gr700xd_3_r": "dispersion/jwst_niriss_gr700xd-ord3_disp_20160902163017.fits",
    "gr700xd_3_wavepix": "wavepix/jwst_niriss_soss-256-ord3_trace_20160929180722.fits",
    "gr700xd_3_wavepix96": "wavepix/jwst_niriss_soss-96-ord3_trace_20160927172406.fits",
    "internal": "optical/jwst_niriss_internaloptics_throughput_20170417172726.fits",
    "ipc_kernel": "../detector/hawaii_2rg_ipc_kernel.fits",
    "nrm": "filters/jwst_niriss_nrm_trans_20160902163017.fits",
    "qe": "qe/jwst_niriss_h2rg_qe_20160902163017.fits",
    "rn_corr": "../detector/h2rg_corr.fits"

The timestamp information from any new fits files delivered would also need to be included.

Note that anything with ../detector/ currently has no timestamp information (the directory may only be available to the ETC folks, ours is empty).

**Comment by jwhite3** [comment]
Closing this and #40 because there's not actually a problem?..
